server:
  port: 8086

spring:
  application:
    name: product

eureka:
  instamce:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # default address