server:
  port: 8085

spring:
  application:
    name: display

hystrix:
  command:
    default: # command Key. use 'default' for global setting.
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # default : 1000
      circuitBreaker:
        requestVolumeThreshold: 1   # Minimum number of request to calculate. circuit breaker's health. default 20
        errorThresholdPercentage: 50  # Error percentage to open circuit. default 50
    productInfo: # commandKey 지정
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
        circuitBreaker:
          requestVolumeThreshold: 1
          errorThresholdPercentage: 50
    FeignProductRemoteService#getProductInfo(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
        circuitBreaker:
          requestVolumeThreshold: 1
          errorThresholdPercentage: 50

product:
  ribbon:
#    listOfServers: localhost:8086,localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1

eureka:
  instamce:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # default address

feign:
  hystrix:
    enabled: true